# Generated by Django 3.0.7 on 2020-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linaPDF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos',
            name='metodo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
